name: Armstrong Validation

on: pull_request

jobs:
  armstrong-validation:
    name: Armstrong Validation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.2

    - name: Install Go Dependencies
      run: |
        go version
        go install github.com/azure/armstrong@c27cb68ad5d83f254f921d594f02b618deb4ad7e
        echo "$(HOME)/go/bin" >> $GITHUB_PATH

    - name: Setup Node and run `npm ci`
      uses: ./.github/actions/setup-node-npm-ci
  
    - name: Print
      run: env | sort

    - name: Armstrong Validation
      run: |
        # Keep processing when errors are written. Nonzero exit will mark the 
        # step as failed. 
        
        ./eng/scripts/Armstrong-Validation.ps1 -RepoOwner -RepoName -PullRequestNumber -AuthToken secrets.GITHUB_TOKEN -Verbose
      shell: pwsh
