name: Armstrong Validation

on: push

jobs:
  pool:
    name: azsdk-pool-mms-ubuntu-2204-general
    vmImage: ubuntu-22.04

  steps:
  - template: ./eng/pipelines/templates/steps/npm-install.yml

  - task: GoTool@0
    inputs:
      version: '1.22.2'
  
  - script: |
      go version
      go install github.com/azure/armstrong@67fe406e78e3b94075932add869f8b11fb4dd0a6
      echo '##vso[task.prependpath]$(HOME)/go/bin'
    displayName: 'Setup dependencies'

  - pwsh: |
      ./eng/scripts/Armstrong-Validation.ps1 -Verbose
    displayName: Armstrong Validation
    ignoreLASTEXITCODE: true
